### ISSUE TITLE
Add builder helpers to docs

### ISSUE THREAD

**Issue by Jibaru** [romanzipp/Laravel-Model-Doc#12]
If you try to use any of the builder helpers that laravel provides, the ide show an alert:
For example, if I use:
```php
MyModel::where('id', 1043);
```
`where` doesn't have a phpdocs.
The same happens with methods like `with`, `find`, `first`, `findMany`, etc.

**Comment by romanzipp** [comment]
Laravel does not ship with a PHPDoc generator out of the box. Could you provide an example before and after code snippet? Which IDE are you using?

**Comment by Jibaru** [comment]
Of course. For example, using the tool, it makes these php docs:
![image](https://user-images.githubusercontent.com/54339832/176342275-6afed5d5-84ee-423d-a0e2-8869d6eb1c30.png)
But, depending the IDE (I'm using PHP Storm), it shows static builder methods or not:
![image](https://user-images.githubusercontent.com/54339832/176342466-d4a1e104-0a46-4265-b736-63940f639316.png)
Only works if I add the `mixin` Builder.
![image](https://user-images.githubusercontent.com/54339832/176342530-339f8f15-9d88-4c3b-a36a-1c184f293738.png)
![image](https://user-images.githubusercontent.com/54339832/176342554-615b104f-b24e-4865-aca2-7b7706d2e9b1.png)

**Comment by romanzipp** [comment]
You can not specify custom mixin tags in the package config like this:

```php
return [
    'custom_tags' => [
        'mixins' => [
            \Illuminate\Database\Eloquent\Model::class,
        ],
    ],
];
```
