### ISSUE TITLE
Resolve additional database column types

### ISSUE THREAD

**Issue by saulens22** [romanzipp/Laravel-Model-Doc#19]
I have recently started using this package and ran into a problem similar to https://github.com/romanzipp/Laravel-Model-Doc/pull/16. After some searching I've found that Laravel has an integrated solution - you just have to add custom casts in `database.php` config file. Here's an example: https://laravel.com/docs/10.x/migrations#modifying-columns-on-sqlite

Adding casts there will work application-wide. So, this package would only need short documentation and maybe better error message showing which type is not defined.

Thanks for this package!

**Comment by romanzipp** [comment]
Could you share and example which column was mapped to a certain type?

**Comment by saulens22** [comment]
I'm using SQL Server in my setup. I believe it should look something like this in `database.php`:
```php
'dbal' => [
    'types' => [
        // exists in MySQL / MariaDB / SQLite
        'enum' => \Doctrine\DBAL\Types\TextType::class,
        'timestamp' => \Illuminate\Database\DBAL\TimestampType::class, // documented by Laravel

        // SQL Server specific types
        'xml' => \Doctrine\DBAL\Types\TextType::class,
        'hierarchyid' => \Doctrine\DBAL\Types\BinaryType::class,

        // works with user-defined types
        'my_custom_type' => \Doctrine\DBAL\Types\TextType::class
    ],
],
```
